# Generated by Django 5.2.1 on 2025-06-01 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_region_is_active_alter_region_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='barangay',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='barangay',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.province'),
        ),
    ]
