# Generated by Django 5.2.1 on 2025-06-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_barangay_is_active_alter_barangay_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
