-- Insert complete list of regions in the Philippines
INSERT INTO region (name) VALUES 
('National Capital Region'),
('Cordillera Administrative Region'),
('Ilocos Region'),
('Cagayan Valley'),
('Central Luzon'),
('CALABARZON'),
('MIMAROPA'),
('Bicol Region'),
('Western Visayas'),
('Central Visayas'),
('Eastern Visayas'),
('Zamboanga Peninsula'),
('Northern Mindanao'),
('Davao Region'),
('SOCCSKSARGEN'),
('Caraga'),
('Bangsamoro Autonomous Region in Muslim Mindanao');

-- Insert complete list of provinces in the Philippines
INSERT INTO province (name, region_id) VALUES 
('Metro Manila', (SELECT id FROM region WHERE name = 'National Capital Region')),
('Abra', (SELECT id FROM region WHERE name = 'Cordillera Administrative Region')),
('Ilocos Norte', (SELECT id FROM region WHERE name = 'Ilocos Region')),
('Ilocos Sur', (SELECT id FROM region WHERE name = 'Ilocos Region')),
('La Union', (SELECT id FROM region WHERE name = 'Ilocos Region')),
('Cagayan', (SELECT id FROM region WHERE name = 'Cagayan Valley')),
('Isabela', (SELECT id FROM region WHERE name = 'Cagayan Valley')),
('Nueva Vizcaya', (SELECT id FROM region WHERE name = 'Cagayan Valley')),
('Quirino', (SELECT id FROM region WHERE name = 'Cagayan Valley')),
('Bulacan', (SELECT id FROM region WHERE name = 'Central Luzon')),
('Pampanga', (SELECT id FROM region WHERE name = 'Central Luzon')),
('Nueva Ecija', (SELECT id FROM region WHERE name = 'Central Luzon')),
('Tarlac', (SELECT id FROM region WHERE name = 'Central Luzon')),
('Zambales', (SELECT id FROM region WHERE name = 'Central Luzon')),
('Bataan', (SELECT id FROM region WHERE name = 'Central Luzon')),
('Laguna', (SELECT id FROM region WHERE name = 'CALABARZON')),
('Cavite', (SELECT id FROM region WHERE name = 'CALABARZON')),
('Batangas', (SELECT id FROM region WHERE name = 'CALABARZON')),
('Rizal', (SELECT id FROM region WHERE name = 'CALABARZON')),
('Quezon', (SELECT id FROM region WHERE name = 'CALABARZON')),
('Palawan', (SELECT id FROM region WHERE name = 'MIMAROPA')),
('Mindoro Occidental', (SELECT id FROM region WHERE name = 'MIMAROPA')),
('Mindoro Oriental', (SELECT id FROM region WHERE name = 'MIMAROPA')),
('Marinduque', (SELECT id FROM region WHERE name = 'MIMAROPA')),
('Romblon', (SELECT id FROM region WHERE name = 'MIMAROPA')),
('Albay', (SELECT id FROM region WHERE name = 'Bicol Region')),
('Camarines Norte', (SELECT id FROM region WHERE name = 'Bicol Region')),
('Camarines Sur', (SELECT id FROM region WHERE name = 'Bicol Region')),
('Catanduanes', (SELECT id FROM region WHERE name = 'Bicol Region')),
('Masbate', (SELECT id FROM region WHERE name = 'Bicol Region')),
('Sorsogon', (SELECT id FROM region WHERE name = 'Bicol Region')),
('Iloilo', (SELECT id FROM region WHERE name = 'Western Visayas')),
('Antique', (SELECT id FROM region WHERE name = 'Western Visayas')),
('Aklan', (SELECT id FROM region WHERE name = 'Western Visayas')),
('Capiz', (SELECT id FROM region WHERE name = 'Western Visayas')),
('Guimaras', (SELECT id FROM region WHERE name = 'Western Visayas')),
('Negros Occidental', (SELECT id FROM region WHERE name = 'Western Visayas')),
('Cebu', (SELECT id FROM region WHERE name = 'Central Visayas')),
('Bohol', (SELECT id FROM region WHERE name = 'Central Visayas')),
('Negros Oriental', (SELECT id FROM region WHERE name = 'Central Visayas')),
('Siquijor', (SELECT id FROM region WHERE name = 'Central Visayas')),
('Leyte', (SELECT id FROM region WHERE name = 'Eastern Visayas')),
('Southern Leyte', (SELECT id FROM region WHERE name = 'Eastern Visayas')),
('Biliran', (SELECT id FROM region WHERE name = 'Eastern Visayas')),
('Samar', (SELECT id FROM region WHERE name = 'Eastern Visayas')),
('Eastern Samar', (SELECT id FROM region WHERE name = 'Eastern Visayas')),
('Northern Samar', (SELECT id FROM region WHERE name = 'Eastern Visayas')),
('Zamboanga del Sur', (SELECT id FROM region WHERE name = 'Zamboanga Peninsula')),
('Zamboanga del Norte', (SELECT id FROM region WHERE name = 'Zamboanga Peninsula')),
('Zamboanga Sibugay', (SELECT id FROM region WHERE name = 'Zamboanga Peninsula')),
('Misamis Oriental', (SELECT id FROM region WHERE name = 'Northern Mindanao')),
('Misamis Occidental', (SELECT id FROM region WHERE name = 'Northern Mindanao')),
('Bukidnon', (SELECT id FROM region WHERE name = 'Northern Mindanao')),
('Camiguin', (SELECT id FROM region WHERE name = 'Northern Mindanao')),
('Lanao del Norte', (SELECT id FROM region WHERE name = 'Northern Mindanao')),
('Davao del Sur', (SELECT id FROM region WHERE name = 'Davao Region')),
('Davao del Norte', (SELECT id FROM region WHERE name = 'Davao Region')),
('Davao Oriental', (SELECT id FROM region WHERE name = 'Davao Region')),
('Davao Occidental', (SELECT id FROM region WHERE name = 'Davao Region')),
('Davao de Oro', (SELECT id FROM region WHERE name = 'Davao Region')),
('South Cotabato', (SELECT id FROM region WHERE name = 'SOCCSKSARGEN')),
('Cotabato', (SELECT id FROM region WHERE name = 'SOCCSKSARGEN')),
('Sultan Kudarat', (SELECT id FROM region WHERE name = 'SOCCSKSARGEN')),
('Sarangani', (SELECT id FROM region WHERE name = 'SOCCSKSARGEN')),
('Agusan del Norte', (SELECT id FROM region WHERE name = 'Caraga')),
('Agusan del Sur', (SELECT id FROM region WHERE name = 'Caraga')),
('Surigao del Norte', (SELECT id FROM region WHERE name = 'Caraga')),
('Surigao del Sur', (SELECT id FROM region WHERE name = 'Caraga')),
('Dinagat Islands', (SELECT id FROM region WHERE name = 'Caraga')),
('Maguindanao', (SELECT id FROM region WHERE name = 'Bangsamoro Autonomous Region in Muslim Mindanao')),
('Lanao del Sur', (SELECT id FROM region WHERE name = 'Bangsamoro Autonomous Region in Muslim Mindanao')),
('Sulu', (SELECT id FROM region WHERE name = 'Bangsamoro Autonomous Region in Muslim Mindanao')),
('Tawi-Tawi', (SELECT id FROM region WHERE name = 'Bangsamoro Autonomous Region in Muslim Mindanao')),
('Basilan', (SELECT id FROM region WHERE name = 'Bangsamoro Autonomous Region in Muslim Mindanao'));

-- Insert initial data for order statuses
INSERT INTO order_status (name) VALUES 
('Pending'),       -- When the order is first placed
('Accepted'),      -- When the order is reviewed and approved
('Dispatched'),    -- When the order is sent out for delivery
('Delivered'),     -- When the order is successfully delivered
('Fulfilled'),     -- When the order is completed and marked as fulfilled
('Cancelled');     -- When the order is rejected or canceled