-- Insert regions if they don't already exist
INSERT INTO region (name) VALUES 
('National Capital Region'),
('Cordillera Administrative Region'),
('Ilocos Region'),
('Cagayan Valley'),
('Central Luzon'),
('CALABARZON'),
('MIMAROPA'),
('Bicol Region'),
('Western Visayas'),
('Central Visayas'),
('Eastern Visayas'),
('Zamboanga Peninsula'),
('Northern Mindanao'),
('Davao Region'),
('SOCCSKSARGEN'),
('Caraga'),
('Bangsamoro Autonomous Region in Muslim Mindanao')
ON CONFLICT (name) DO NOTHING;

-- Insert provinces if they don't already exist
INSERT INTO province (name, region_id) VALUES 
('Metro Manila', (SELECT id FROM region WHERE name = 'National Capital Region')),
('Abra', (SELECT id FROM region WHERE name = 'Cordillera Administrative Region')),
('Ilocos Norte', (SELECT id FROM region WHERE name = 'Ilocos Region')),
('Ilocos Sur', (SELECT id FROM region WHERE name = 'Ilocos Region')),
('La Union', (SELECT id FROM region WHERE name = 'Ilocos Region')),
('Cagayan', (SELECT id FROM region WHERE name = 'Cagayan Valley')),
('Isabela', (SELECT id FROM region WHERE name = 'Cagayan Valley')),
('Nueva Vizcaya', (SELECT id FROM region WHERE name = 'Cagayan Valley')),
('Quirino', (SELECT id FROM region WHERE name = 'Cagayan Valley')),
('Bulacan', (SELECT id FROM region WHERE name = 'Central Luzon')),
('Pampanga', (SELECT id FROM region WHERE name = 'Central Luzon')),
('Nueva Ecija', (SELECT id FROM region WHERE name = 'Central Luzon')),
('Tarlac', (SELECT id FROM region WHERE name = 'Central Luzon')),
('Zambales', (SELECT id FROM region WHERE name = 'Central Luzon')),
('Bataan', (SELECT id FROM region WHERE name = 'Central Luzon')),
('Laguna', (SELECT id FROM region WHERE name = 'CALABARZON')),
('Cavite', (SELECT id FROM region WHERE name = 'CALABARZON')),
('Batangas', (SELECT id FROM region WHERE name = 'CALABARZON')),
('Rizal', (SELECT id FROM region WHERE name = 'CALABARZON')),
('Quezon', (SELECT id FROM region WHERE name = 'CALABARZON')),
('Palawan', (SELECT id FROM region WHERE name = 'MIMAROPA')),
('Mindoro Occidental', (SELECT id FROM region WHERE name = 'MIMAROPA')),
('Mindoro Oriental', (SELECT id FROM region WHERE name = 'MIMAROPA')),
('Marinduque', (SELECT id FROM region WHERE name = 'MIMAROPA')),
('Romblon', (SELECT id FROM region WHERE name = 'MIMAROPA')),
('Albay', (SELECT id FROM region WHERE name = 'Bicol Region')),
('Camarines Norte', (SELECT id FROM region WHERE name = 'Bicol Region')),
('Camarines Sur', (SELECT id FROM region WHERE name = 'Bicol Region')),
('Catanduanes', (SELECT id FROM region WHERE name = 'Bicol Region')),
('Masbate', (SELECT id FROM region WHERE name = 'Bicol Region')),
('Sorsogon', (SELECT id FROM region WHERE name = 'Bicol Region')),
('Iloilo', (SELECT id FROM region WHERE name = 'Western Visayas')),
('Antique', (SELECT id FROM region WHERE name = 'Western Visayas')),
('Aklan', (SELECT id FROM region WHERE name = 'Western Visayas')),
('Capiz', (SELECT id FROM region WHERE name = 'Western Visayas')),
('Guimaras', (SELECT id FROM region WHERE name = 'Western Visayas')),
('Negros Occidental', (SELECT id FROM region WHERE name = 'Western Visayas')),
('Cebu', (SELECT id FROM region WHERE name = 'Central Visayas')),
('Bohol', (SELECT id FROM region WHERE name = 'Central Visayas')),
('Negros Oriental', (SELECT id FROM region WHERE name = 'Central Visayas')),
('Siquijor', (SELECT id FROM region WHERE name = 'Central Visayas')),
('Leyte', (SELECT id FROM region WHERE name = 'Eastern Visayas')),
('Southern Leyte', (SELECT id FROM region WHERE name = 'Eastern Visayas')),
('Biliran', (SELECT id FROM region WHERE name = 'Eastern Visayas')),
('Samar', (SELECT id FROM region WHERE name = 'Eastern Visayas')),
('Eastern Samar', (SELECT id FROM region WHERE name = 'Eastern Visayas')),
('Northern Samar', (SELECT id FROM region WHERE name = 'Eastern Visayas')),
('Zamboanga del Sur', (SELECT id FROM region WHERE name = 'Zamboanga Peninsula')),
('Zamboanga del Norte', (SELECT id FROM region WHERE name = 'Zamboanga Peninsula')),
('Zamboanga Sibugay', (SELECT id FROM region WHERE name = 'Zamboanga Peninsula')),
('Misamis Oriental', (SELECT id FROM region WHERE name = 'Northern Mindanao')),
('Misamis Occidental', (SELECT id FROM region WHERE name = 'Northern Mindanao')),
('Bukidnon', (SELECT id FROM region WHERE name = 'Northern Mindanao')),
('Camiguin', (SELECT id FROM region WHERE name = 'Northern Mindanao')),
('Lanao del Norte', (SELECT id FROM region WHERE name = 'Northern Mindanao')),
('Davao del Sur', (SELECT id FROM region WHERE name = 'Davao Region')),
('Davao del Norte', (SELECT id FROM region WHERE name = 'Davao Region')),
('Davao Oriental', (SELECT id FROM region WHERE name = 'Davao Region')),
('Davao Occidental', (SELECT id FROM region WHERE name = 'Davao Region')),
('Davao de Oro', (SELECT id FROM region WHERE name = 'Davao Region')),
('South Cotabato', (SELECT id FROM region WHERE name = 'SOCCSKSARGEN')),
('Cotabato', (SELECT id FROM region WHERE name = 'SOCCSKSARGEN')),
('Sultan Kudarat', (SELECT id FROM region WHERE name = 'SOCCSKSARGEN')),
('Sarangani', (SELECT id FROM region WHERE name = 'SOCCSKSARGEN')),
('Agusan del Norte', (SELECT id FROM region WHERE name = 'Caraga')),
('Agusan del Sur', (SELECT id FROM region WHERE name = 'Caraga')),
('Surigao del Norte', (SELECT id FROM region WHERE name = 'Caraga')),
('Surigao del Sur', (SELECT id FROM region WHERE name = 'Caraga')),
('Dinagat Islands', (SELECT id FROM region WHERE name = 'Caraga')),
('Maguindanao', (SELECT id FROM region WHERE name = 'Bangsamoro Autonomous Region in Muslim Mindanao')),
('Lanao del Sur', (SELECT id FROM region WHERE name = 'Bangsamoro Autonomous Region in Muslim Mindanao')),
('Sulu', (SELECT id FROM region WHERE name = 'Bangsamoro Autonomous Region in Muslim Mindanao')),
('Tawi-Tawi', (SELECT id FROM region WHERE name = 'Bangsamoro Autonomous Region in Muslim Mindanao')),
('Basilan', (SELECT id FROM region WHERE name = 'Bangsamoro Autonomous Region in Muslim Mindanao'))
ON CONFLICT (name, region_id) DO NOTHING;

-- Insert barangays if they don't already exist
INSERT INTO barangay (name, province_id) VALUES 
('Agtangao', (SELECT id FROM province WHERE name = 'Abra')),
('Angad', (SELECT id FROM province WHERE name = 'Abra')),
('Bangbangar', (SELECT id FROM province WHERE name = 'Abra')),
('Bañacao', (SELECT id FROM province WHERE name = 'Abra')),
('Cabuloan', (SELECT id FROM province WHERE name = 'Abra')),
('Calaba', (SELECT id FROM province WHERE name = 'Abra')),
('Cosili East', (SELECT id FROM province WHERE name = 'Abra')),
('Cosili West', (SELECT id FROM province WHERE name = 'Abra')),
('Dangdangla', (SELECT id FROM province WHERE name = 'Abra')),
('Lingtan', (SELECT id FROM province WHERE name = 'Abra')),
('Lipcan', (SELECT id FROM province WHERE name = 'Abra')),
('Lubong', (SELECT id FROM province WHERE name = 'Abra')),
('Macarcarmay', (SELECT id FROM province WHERE name = 'Abra')),
('Macray', (SELECT id FROM province WHERE name = 'Abra')),
('Malita', (SELECT id FROM province WHERE name = 'Abra')),
('Maoay', (SELECT id FROM province WHERE name = 'Abra')),
('Palao', (SELECT id FROM province WHERE name = 'Abra')),
('Patucannay', (SELECT id FROM province WHERE name = 'Abra')),
('Sagap', (SELECT id FROM province WHERE name = 'Abra')),
('San Antonio', (SELECT id FROM province WHERE name = 'Abra')),
('Santa Rosa', (SELECT id FROM province WHERE name = 'Abra')),
('Sao-atan', (SELECT id FROM province WHERE name = 'Abra')),
('Sappaac', (SELECT id FROM province WHERE name = 'Abra')),
('Tablac', (SELECT id FROM province WHERE name = 'Abra')),
('Zone 1 Poblacion', (SELECT id FROM province WHERE name = 'Abra')),
('Zone 2 Poblacion', (SELECT id FROM province WHERE name = 'Abra')),
('Zone 3 Poblacion', (SELECT id FROM province WHERE name = 'Abra')),
('Zone 4 Poblacion', (SELECT id FROM province WHERE name = 'Abra')),
('Zone 5 Poblacion', (SELECT id FROM province WHERE name = 'Abra')),
('Zone 6 Poblacion', (SELECT id FROM province WHERE name = 'Abra')),
('Zone 7 Poblacion', (SELECT id FROM province WHERE name = 'Abra')),
('Amti', (SELECT id FROM province WHERE name = 'Abra')),
('Bao-yan', (SELECT id FROM province WHERE name = 'Abra')),
('Danac East', (SELECT id FROM province WHERE name = 'Abra')),
('Danac West', (SELECT id FROM province WHERE name = 'Abra')),
('Dao-angan', (SELECT id FROM province WHERE name = 'Abra')),
('Dumagas', (SELECT id FROM province WHERE name = 'Abra')),
('Kilong-Olao', (SELECT id FROM province WHERE name = 'Abra')),
('Poblacion', (SELECT id FROM province WHERE name = 'Abra')),
('Abang', (SELECT id FROM province WHERE name = 'Abra')),
('Bangbangcag', (SELECT id FROM province WHERE name = 'Abra')),
('Bangcagan', (SELECT id FROM province WHERE name = 'Abra')),
('Banglolao', (SELECT id FROM province WHERE name = 'Abra')),
('Bugbog', (SELECT id FROM province WHERE name = 'Abra')),
('Calao', (SELECT id FROM province WHERE name = 'Abra')),
('Dugong', (SELECT id FROM province WHERE name = 'Abra')),
('Labon', (SELECT id FROM province WHERE name = 'Abra')),
('Layugan', (SELECT id FROM province WHERE name = 'Abra')),
('Madalipay', (SELECT id FROM province WHERE name = 'Abra')),
('North Poblacion', (SELECT id FROM province WHERE name = 'Abra')),
('Pagala', (SELECT id FROM province WHERE name = 'Abra')),
('Pakiling', (SELECT id FROM province WHERE name = 'Abra')),
('Palaquio', (SELECT id FROM province WHERE name = 'Abra')),
('Patoc', (SELECT id FROM province WHERE name = 'Abra')),
('Quimloong', (SELECT id FROM province WHERE name = 'Abra')),
('Salnec', (SELECT id FROM province WHERE name = 'Abra')),
('San Miguel', (SELECT id FROM province WHERE name = 'Abra')),
('Siblong', (SELECT id FROM province WHERE name = 'Abra')),
('South Poblacion', (SELECT id FROM province WHERE name = 'Abra')),
('Tabiog', (SELECT id FROM province WHERE name = 'Abra')),
('Ducligan', (SELECT id FROM province WHERE name = 'Abra')),
('Labaan', (SELECT id FROM province WHERE name = 'Abra')),
('Lamao', (SELECT id FROM province WHERE name = 'Abra')),
('Lingay', (SELECT id FROM province WHERE name = 'Abra')),
('Ableg', (SELECT id FROM province WHERE name = 'Abra')),
('Cabaruyan', (SELECT id FROM province WHERE name = 'Abra')),
('Pikek', (SELECT id FROM province WHERE name = 'Abra')),
('Tui', (SELECT id FROM province WHERE name = 'Abra')),
('Abaquid', (SELECT id FROM province WHERE name = 'Abra')),
('Cabaruan', (SELECT id FROM province WHERE name = 'Abra')),
('Caupasan', (SELECT id FROM province WHERE name = 'Abra')),
('Danglas', (SELECT id FROM province WHERE name = 'Abra')),
('Nagaparan', (SELECT id FROM province WHERE name = 'Abra')),
('Padangitan', (SELECT id FROM province WHERE name = 'Abra')),
('Pangal', (SELECT id FROM province WHERE name = 'Abra')),

('Abilan', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Agong-ong', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Alubijid', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Guinabsan', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Lower Olave', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Macalang', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Malapong', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Malpoc', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Manapa', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Matabao', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Poblacion 1', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Poblacion 10', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Poblacion 2', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Poblacion 3', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Poblacion 4', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Poblacion 5', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Poblacion 6', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Poblacion 7', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Poblacion 8', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Poblacion 9', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Rizal', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Sacol', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Sangay', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Simbalan', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Talo-ao', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Antonio Luna', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Bay-ang', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Bayabas', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Caasinan', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Cabinet', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Calamba', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Calibunan', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Comagascas', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Concepcion', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Del Pilar', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Katugasan', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Kauswagan', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('La Union', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Mabini', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Mahaba', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Puting Bato', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Sanghan', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Soriano', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Tolosa', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Cahayagan', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Gosoon', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Manoligao', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Poblacion', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Rojales', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('San Agustin', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Tagcatong', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Vinapor', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('A. Beltran', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Baleguian', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Bangonay', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Bunga', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Colorado', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Cuyago', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Libas', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Magdagooc', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Magsaysay', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Maraiging', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('San Jose', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('San Pablo', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('San Vicente', (SELECT id FROM province WHERE name = 'Agusan del Norte')),
('Santo Niño', (SELECT id FROM province WHERE name = 'Agusan del Norte')),

('Berseba', (SELECT id FROM province WHERE name = 'Agusan del Sur')),
('Bucac', (SELECT id FROM province WHERE name = 'Agusan del Sur')),
('Cagbas', (SELECT id FROM province WHERE name = 'Agusan del Sur')),
('Calaitan', (SELECT id FROM province WHERE name = 'Agusan del Sur')),
('Canayugan', (SELECT id FROM province WHERE name = 'Agusan del Sur')),
('Charito', (SELECT id FROM province WHERE name = 'Agusan del Sur')),
('Claro Cortez', (SELECT id FROM province WHERE name = 'Agusan del Sur')),
('Fili', (SELECT id FROM province WHERE name = 'Agusan del Sur')),
('Gamao', (SELECT id FROM province WHERE name = 'Agusan del Sur')),
('Getsemane', (SELECT id FROM province WHERE name = 'Agusan del Sur')),
('Grace Estate', (SELECT id FROM province WHERE name = 'Agusan del Sur')),
('Hamogaway', (SELECT id FROM province WHERE name = 'Agusan del Sur')),
('Katipunan', (SELECT id FROM province WHERE name = 'Agusan del Sur')),
('Mabuhay', (SELECT id FROM province WHERE name = 'Agusan del Sur')),
('Magkiangkang', (SELECT id FROM province WHERE name = 'Agusan del Sur')),
('Mahayag', (SELECT id FROM province WHERE name = 'Agusan del Sur')),
('Marcelina', (SELECT id FROM province WHERE name = 'Agusan del Sur')),
('Maygatasan', (SELECT id FROM province WHERE name = 'Agusan del Sur')),
('Montivesta', (SELECT id FROM province WHERE name = 'Agusan del Sur')),
('Mt. Ararat', (SELECT id FROM province WHERE name = 'Agusan del Sur')),
('Mt. Carmel', (SELECT id FROM province WHERE name = 'Agusan del Sur')),
('Mt. Olive', (SELECT id FROM province WHERE name = 'Agusan del Sur')),
('New Salem', (SELECT id FROM province WHERE name = 'Agusan del Sur')),
('Noli', (SELECT id FROM province WHERE name = 'Agusan del Sur')),
('Osmeña', (SELECT id FROM province WHERE name = 'Agusan del Sur')),
('Panaytay', (SELECT id FROM province WHERE name = 'Agusan del Sur')),
('Pinagalaan', (SELECT id FROM province WHERE name = 'Agusan del Sur')),
('Poblacion', (SELECT id FROM province WHERE name = 'Agusan del Sur')),
('Sagmone', (SELECT id FROM province WHERE name = 'Agusan del Sur')),
('Saguma', (SELECT id FROM province WHERE name = 'Agusan del Sur')),
('Salvacion', (SELECT id FROM province WHERE name = 'Agusan del Sur')),
('San Agustin', (SELECT id FROM province WHERE name = 'Agusan del Sur')),
('San Isidro', (SELECT id FROM province WHERE name = 'Agusan del Sur')),
('San Juan', (SELECT id FROM province WHERE name = 'Agusan del Sur')),
('Santa Irene', (SELECT id FROM province WHERE name = 'Agusan del Sur')),
('Santa Teresita', (SELECT id FROM province WHERE name = 'Agusan del Sur')),
('Santo Niño', (SELECT id FROM province WHERE name = 'Agusan del Sur')),
('Taglatawan', (SELECT id FROM province WHERE name = 'Agusan del Sur')),
('Taglibas', (SELECT id FROM province WHERE name = 'Agusan del Sur')),
('Tagubay', (SELECT id FROM province WHERE name = 'Agusan del Sur')),
('Verdu', (SELECT id FROM province WHERE name = 'Agusan del Sur')),
('Villa Undayon', (SELECT id FROM province WHERE name = 'Agusan del Sur')),
('Wawa', (SELECT id FROM province WHERE name = 'Agusan del Sur')),

('Cabadiangan, Alcantara', (SELECT id FROM province WHERE name = 'Cebu')),
('Cabil-isan, Alcantara', (SELECT id FROM province WHERE name = 'Cebu')),
('Candabong, Alcantara', (SELECT id FROM province WHERE name = 'Cebu')),
('Lawaan, Alcantara', (SELECT id FROM province WHERE name = 'Cebu')),
('Manga, Alcantara', (SELECT id FROM province WHERE name = 'Cebu')),
('Palanas, Alcantara', (SELECT id FROM province WHERE name = 'Cebu')),
('Poblacion, Alcantara', (SELECT id FROM province WHERE name = 'Cebu')),
('Polo, Alcantara', (SELECT id FROM province WHERE name = 'Cebu')),
('Salagmaya, Alcantara', (SELECT id FROM province WHERE name = 'Cebu')),
('Atabay, Alcoy', (SELECT id FROM province WHERE name = 'Cebu')),
('Daan-Lungsod, Alcoy', (SELECT id FROM province WHERE name = 'Cebu')),
('Guiwang, Alcoy', (SELECT id FROM province WHERE name = 'Cebu')),
('Nug-as, Alcoy', (SELECT id FROM province WHERE name = 'Cebu')),
('Pasol, Alcoy', (SELECT id FROM province WHERE name = 'Cebu')),
('Poblacion, Alcoy', (SELECT id FROM province WHERE name = 'Cebu')),
('Pugalo, Alcoy', (SELECT id FROM province WHERE name = 'Cebu')),
('San Agustin, Alcoy', (SELECT id FROM province WHERE name = 'Cebu')),
('Compostela, Alegria', (SELECT id FROM province WHERE name = 'Cebu')),
('Guadalupe, Alegria', (SELECT id FROM province WHERE name = 'Cebu')),
('Legaspi, Alegria', (SELECT id FROM province WHERE name = 'Cebu')),
('Lepanto, Alegria', (SELECT id FROM province WHERE name = 'Cebu')),
('Madridejos, Alegria', (SELECT id FROM province WHERE name = 'Cebu')),
('Montpeller, Alegria', (SELECT id FROM province WHERE name = 'Cebu')),
('Poblacion, Alegria', (SELECT id FROM province WHERE name = 'Cebu')),
('Santa Filomena, Alegria', (SELECT id FROM province WHERE name = 'Cebu')),
('Valencia, Alegria', (SELECT id FROM province WHERE name = 'Cebu')),
('Angilan, Aloguinsan', (SELECT id FROM province WHERE name = 'Cebu')),
('Bojo, Aloguinsan', (SELECT id FROM province WHERE name = 'Cebu')),
('Bonbon, Aloguinsan', (SELECT id FROM province WHERE name = 'Cebu')),
('Esperanza, Aloguinsan', (SELECT id FROM province WHERE name = 'Cebu')),
('Kandingan, Aloguinsan', (SELECT id FROM province WHERE name = 'Cebu')),
('Kantabogon, Aloguinsan', (SELECT id FROM province WHERE name = 'Cebu')),
('Kawasan, Aloguinsan', (SELECT id FROM province WHERE name = 'Cebu')),
('Olango, Aloguinsan', (SELECT id FROM province WHERE name = 'Cebu')),
('Poblacion, Aloguinsan', (SELECT id FROM province WHERE name = 'Cebu')),
('Punay, Aloguinsan', (SELECT id FROM province WHERE name = 'Cebu')),
('Rosario, Aloguinsan', (SELECT id FROM province WHERE name = 'Cebu')),
('Saksak, Aloguinsan', (SELECT id FROM province WHERE name = 'Cebu')),
('Tampa-an, Aloguinsan', (SELECT id FROM province WHERE name = 'Cebu')),
('Toyokon, Aloguinsan', (SELECT id FROM province WHERE name = 'Cebu')),
('Zaragosa, Aloguinsan', (SELECT id FROM province WHERE name = 'Cebu')),
('Alambijud, Argao', (SELECT id FROM province WHERE name = 'Cebu')),
('Anajao, Argao', (SELECT id FROM province WHERE name = 'Cebu')),
('Apo, Argao', (SELECT id FROM province WHERE name = 'Cebu')),
('Balaas, Argao', (SELECT id FROM province WHERE name = 'Cebu')),
('Balisong, Argao', (SELECT id FROM province WHERE name = 'Cebu')),
('Binlod, Argao', (SELECT id FROM province WHERE name = 'Cebu')),
('Bogo, Argao', (SELECT id FROM province WHERE name = 'Cebu')),
('Bug-ot, Argao', (SELECT id FROM province WHERE name = 'Cebu')),
('Bulasa, Argao', (SELECT id FROM province WHERE name = 'Cebu')),
('Butong, Argao', (SELECT id FROM province WHERE name = 'Cebu')),
('Calagasan, Argao', (SELECT id FROM province WHERE name = 'Cebu')),
('Canbantug, Argao', (SELECT id FROM province WHERE name = 'Cebu')),
('Canbanua, Argao', (SELECT id FROM province WHERE name = 'Cebu')),
('Cansuje, Argao', (SELECT id FROM province WHERE name = 'Cebu')),
('Capio-an, Argao', (SELECT id FROM province WHERE name = 'Cebu')),
('Casay, Argao', (SELECT id FROM province WHERE name = 'Cebu')),
('Catang, Argao', (SELECT id FROM province WHERE name = 'Cebu')),
('Colawin, Argao', (SELECT id FROM province WHERE name = 'Cebu')),
('Conalum, Argao', (SELECT id FROM province WHERE name = 'Cebu')),
('Guiwanon, Argao', (SELECT id FROM province WHERE name = 'Cebu')),
('Gutlang, Argao', (SELECT id FROM province WHERE name = 'Cebu')),
('Jampang, Argao', (SELECT id FROM province WHERE name = 'Cebu')),
('Jomgao, Argao', (SELECT id FROM province WHERE name = 'Cebu')),
('Lamacan, Argao', (SELECT id FROM province WHERE name = 'Cebu')),
('Langtad, Argao', (SELECT id FROM province WHERE name = 'Cebu')),
('Langub, Argao', (SELECT id FROM province WHERE name = 'Cebu')),
('Lapay, Argao', (SELECT id FROM province WHERE name = 'Cebu')),
('Lengigon, Argao', (SELECT id FROM province WHERE name = 'Cebu')),
('Linut-od, Argao', (SELECT id FROM province WHERE name = 'Cebu')),
('Mabasa, Argao', (SELECT id FROM province WHERE name = 'Cebu')),
('Mandilikit, Argao', (SELECT id FROM province WHERE name = 'Cebu')),
('Mompeller, Argao', (SELECT id FROM province WHERE name = 'Cebu')),
('Panadtaran, Argao', (SELECT id FROM province WHERE name = 'Cebu')),
('Poblacion, Argao', (SELECT id FROM province WHERE name = 'Cebu')),
('Sua, Argao', (SELECT id FROM province WHERE name = 'Cebu')),
('Sumaguan, Argao', (SELECT id FROM province WHERE name = 'Cebu')),
('Tabayag, Argao', (SELECT id FROM province WHERE name = 'Cebu')),
('Talaga, Argao', (SELECT id FROM province WHERE name = 'Cebu')),
('Talaytay, Argao', (SELECT id FROM province WHERE name = 'Cebu')),
('Talo-ot, Argao', (SELECT id FROM province WHERE name = 'Cebu')),
('Tiguib, Argao', (SELECT id FROM province WHERE name = 'Cebu')),
('Tulang, Argao', (SELECT id FROM province WHERE name = 'Cebu')),
('Tulic, Argao', (SELECT id FROM province WHERE name = 'Cebu')),
('Ubaub, Argao', (SELECT id FROM province WHERE name = 'Cebu')),
('Usmad, Argao', (SELECT id FROM province WHERE name = 'Cebu'))
ON CONFLICT (name, province_id) DO NOTHING;

-- Insert initial data for order statuses
INSERT INTO order_status (name) VALUES 
('Pending'),       -- When the order is first placed
('Accepted'),      -- When the order is reviewed and approved
('Dispatched'),    -- When the order is sent out for delivery
('Delivered'),     -- When the order is successfully delivered
('Fulfilled'),     -- When the order is completed and marked as fulfilled
('Cancelled')      -- When the order is rejected or canceled
ON CONFLICT (name) DO NOTHING;