# Generated by Django 5.2.1 on 2025-06-01 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('customers', '0003_customer_created_at_customer_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='barangay',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.barangay'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.province'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.region'),
            preserve_default=False,
        ),
    ]
